[project]
name = "tobi-de"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "coltrane[json5,compressor]",
    "feedparser",
]
