name: Update README with recent activity

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 */1 * *" # Run every day at 4:00 UTC
  workflow_dispatch:

jobs:
  recent-activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}